### ISSUE TITLE
You need to manually create the Data folder in the game directory

### ISSUE THREAD

**Issue by tigerknee1** [Didnapper/Didnapper#9]
At first when I ran the encoder it looked as if it was doing something but didn't create any rxdata files.
Then when I created the folder Data in the directory with game.exe it successfully created all the files.

Easy to work around but can be confusing.

**Comment by tasadar2** [comment]
This was fixed in RpgMakerEncoder https://github.com/tasadar2/RpgMakerEncoder/pull/1, but might not have been updated here. The tool could probably use an auto update to resolve future issues.
